Repository chicago-tool-library/circulate, pull requests merged in 2020-10, with the labels that each got.

#299 update category nav helper and styles to make labels more readable
  app/helpers/items_helper.rb
  app/javascript/stylesheets/application.scss
Labels: UX / Usability, enhancement, hacktoberfest

#302 add nodejs and yarn to asdf tool-versions
  .tool-versions
Labels: documentation

#301 Redirect members to My Loans page and admin users to Admin page
  app/controllers/application_controller.rb
  test/controllers/application_controller_test.rb
Labels: hacktoberfest-accepted

#313 Fixed message in appointments page and adjusted display of date. Fixes Issue #311 and #312
  app/javascript/stylesheets/partials/_admin_appointments.scss
  app/javascript/stylesheets/partials/_index.scss
  app/views/admin/appointments/index.html.erb
Labels: hacktoberfest-accepted

#326 Fixed internal error when navigating to pages that require login. Issue#316
  app/controllers/appointments_controller.rb
  app/controllers/member_holds_controller.rb
  app/controllers/member_profiles/passwords_controller.rb
  app/controllers/member_profiles_controller.rb
  app/controllers/members_controller.rb
Labels: hacktoberfest-accepted

#328 Redirect users to originating page after login
  app/controllers/application_controller.rb
  app/controllers/users/sessions_controller.rb
  config/routes.rb
  test/controllers/application_controller_test.rb
Labels: hacktoberfest-accepted
