Repository chicago-tool-library/circulate, pull requests merged in 2020-09, with the labels that each got.

#141 Add install step
  README.md
Labels: documentation

#146 Updated the outdated bundled gems to newest versions
  Gemfile.lock
  package.json
  yarn.lock
Labels: Ruby For Good 🎃 Fall 2020, dependencies

#231 Create table, model for appointment and appointment holds
  app/models/appointment.rb
  app/models/appointment_hold.rb
  app/models/member.rb
  db/migrate/20200923151427_create_appointments.rb
  db/migrate/20200923152956_create_appointment_holds.rb
  db/schema.rb
  test/factories/appointment_holds.rb
  test/factories/appointments.rb
  test/models/appointment_hold_test.rb
  test/models/appointment_test.rb
Labels: :zap: Power :zap:

#217 Login Page Refresh
  .gitignore
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/partials/_index.scss
  app/javascript/stylesheets/partials/_users_password_new.scss
  app/javascript/stylesheets/partials/_users_sign_in.scss
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
Labels: :zap: Power :zap:, UX / Usability

#214 Displays the members items that are on hold
  app/controllers/members_controller.rb
  app/helpers/holds_helper.rb
  app/models/hold.rb
  app/views/members/loans.html.erb
  config/routes.rb
Labels: :zap: Power :zap:

#233 Create listing page for appointments in admin area
  app/controllers/admin/appointments_controller.rb
  app/helpers/appointments_helper.rb
  app/views/admin/appointments/index.html.erb
  app/views/layouts/admin.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: :zap: Power :zap:

#223 Implement place on hold button functionality for items
  app/controllers/items_controller.rb
  app/controllers/member_holds_controller.rb
  app/models/borrow_policy.rb
  app/models/hold.rb
  app/models/item.rb
  app/views/items/place_hold_on/_item.html.erb
  app/views/items/place_hold_on/_item_already_with_a_hold.html.erb
  app/views/items/place_hold_on/_item_that_allows_multiple_holds.html.erb
  app/views/items/place_hold_on/_not_logged_in.html.erb
  app/views/items/show.html.erb
  config/routes.rb
  test/controllers/member_holds_controller.rb
  test/models/borrow_policy_test.rb
  test/system/member_holds_test.rb
Labels: :zap: Power :zap:

#236 Navbar and Sidebar Mobile Redesign
  .tool-versions
  app/javascript/stylesheets/partials/_index.scss
  app/javascript/stylesheets/partials/_member_navbar.scss
  app/views/layouts/_user.html.erb
  app/views/layouts/application.html.erb
Labels: :zap: Power :zap:, UX / Usability

#238 Appointment details page for pickups and returns
  app/controllers/admin/appointment_checkins_controller.rb
  app/controllers/admin/appointment_checkouts_controller.rb
  app/controllers/admin/appointments_controller.rb
  app/models/appointment.rb
  app/models/appointment_loan.rb
  app/models/hold.rb
  app/models/loan.rb
  app/views/admin/appointments/_checkins.html.erb
  app/views/admin/appointments/_checkouts.html.erb
  app/views/admin/appointments/show.html.erb
  app/views/admin/members/_member_details.html.erb
  app/views/admin/members/_profile.html.erb
  config/routes.rb
  db/migrate/20200924184016_create_appointment_loans.rb
  db/schema.rb
  test/controllers/member_holds_controller.rb
  test/factories/appointment_loans.rb
  test/models/appointment_loan_test.rb
  test/system/member_profile_test.rb
Labels: :zap: Power :zap:

#242 Add checkins to appointment detail page
  app/views/admin/appointments/_checkins.html.erb
  app/views/admin/appointments/_checkouts.html.erb
  app/views/admin/appointments/index.html.erb
  app/views/admin/appointments/show.html.erb
Labels: :zap: Power :zap:

#245 Add and implement remove button for checkin and checkout items
  app/controllers/admin/appointment_holds_controller.rb
  app/controllers/admin/appointment_loans_controller.rb
  app/views/admin/appointments/_checkins.html.erb
  app/views/admin/appointments/_checkouts.html.erb
  app/views/admin/appointments/show.html.erb
  config/routes.rb
Labels: :zap: Power :zap:

#230 Members can create a new appointment
  Gemfile
  Gemfile.lock
  app/controllers/appointments_controller.rb
  app/lib/open_days.rb
  app/models/appointment.rb
  app/models/hold.rb
  app/views/appointments/new.html.erb
  app/views/members/loans.html.erb
  config/initializers/chronic.rb
  config/routes.rb
  test/lib/open_days_test.rb
Labels: :zap: Power :zap:

#247 Implement cancel appointment functionality
  app/controllers/admin/appointments_controller.rb
  app/helpers/appointments_helper.rb
  app/models/appointment.rb
  app/views/admin/appointments/index.html.erb
  app/views/admin/appointments/show.html.erb
  config/routes.rb
Labels: :zap: Power :zap:

#250 Fix btn-link naming conflict
  app/javascript/stylesheets/globals.scss
  app/views/admin/dev/styles.html.erb
Labels: :zap: Power :zap:, UX / Usability

#240 Upcoming Appointments Page
  app/controllers/application_controller.rb
  app/controllers/appointments_controller.rb
  app/javascript/stylesheets/partials/_appointments.scss
  app/javascript/stylesheets/partials/_index.scss
  app/models/appointment.rb
  app/views/appointments/_form.html.erb
  app/views/appointments/index.html.erb
  app/views/appointments/new.html.erb
  app/views/layouts/_user.html.erb
  app/views/members/loans.html.erb
  config/initializers/chronic.rb
  config/routes.rb
  test/lib/open_days_test.rb
Labels: :zap: Power :zap:

#248 Implement item addition to appointment
  app/controllers/admin/appointment_checkouts_controller.rb
  app/controllers/admin/appointment_holds_controller.rb
  app/controllers/admin/appointments_controller.rb
  app/models/item.rb
  app/views/admin/appointments/_checkouts.html.erb
  app/views/admin/appointments/show.html.erb
  config/routes.rb
Labels: :zap: Power :zap:
